services:
  dev:
    build: .
    ports:
      - "3000:3000"
      - "8081:8081"
      - "5000:5000"
    volumes:
      - .:/root/Capstone
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database/create_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
